[package]
name = "multiparse"
description = "Automatically parse multiple radices"
license = "MIT OR Apache-2.0"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/JMANN240/multiparse"

[dependencies]
num-traits = "0.2.19"
